export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_COMPLETE = 'FETCH_PROFILE_COMPLETE';
export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_COMPLETE = 'ADD_PROFILE_COMPLETE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_COMPLETE = 'UPDATE_PROFILE_COMPLETE';